# Generated by Django 4.2 on 2023-04-27 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=30, verbose_name='Név')),
            ],
        ),
        migrations.CreateModel(
            name='Ingatlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leiras', models.TextField(blank=True, null=True, verbose_name='Leírás')),
                ('hirdetes_datuma', models.DateField(blank=True, null=True, verbose_name='Hirdetés ideje')),
                ('tehermentes', models.BooleanField(verbose_name='Tehermentes')),
                ('ar', models.IntegerField(verbose_name='Ár')),
                ('kep_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kép URL')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kategoria', verbose_name='Kategória')),
            ],
        ),
    ]
