# Generated by Django 4.2 on 2023-04-27 08:42

from django.db import migrations

def adatokFeltoltese(apps, schema_editor):
    Kategoria = apps.get_model('app', 'Kategoria')

    kategoriak = ['Ház', 'Lakás', 'Építési telek', 'Garázs', 'Mezőgazdasági terület', 'Ipari ingatlan']

    for i in range(len(kategoriak)):
        k = Kategoria(i + 1, kategoriak[i])
        k.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(adatokFeltoltese)
    ]
